spring:
  config:
    activate:
      on-profile: local
  application:
    name: lab-notification
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/lab?useSSL=false&characterEncoding=UTF8
    username: root
    password: root

server:
  port: 9090

logging:
  file:
    path: /lab/lab-notification/logs/lab-notification

service:
  mode: server
